language: java

cache:
  directories:
    - '$HOME/.m2'

env:
  CLI_TOOLS_VERSION: '1.10.0.414'

jobs:
  include:
    - stage: deploy
      before_install:
        # cli tools
        - |
          curl -O https://download.clojure.org/install/linux-install-${CLI_TOOLS_VERSION}.sh
          chmod +x linux-install-${CLI_TOOLS_VERSION}.sh
          sudo ./linux-install-${CLI_TOOLS_VERSION}.sh
        - 'nvm install 10'
        - 'npm install -g yarn'
      install:
        - 'yarn install'
        - 'clojure -Stree'
      script:
        - 'yarn run build'
        - 'echo "{:closure-defines {app.config/sentry-dsn \"${SENTRY_DSN}\"}}" > options.cljs.edn'
        - 'clojure -m figwheel.main --build-once options:min'
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: resources/public
        target-branch: gh-pages
        on:
          branch: master
